// Auth types
export const SIGNIN_STARTED = 'SIGNIN_STARTED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const LOCAL_SIGNIN_FAILED = 'LOCAL_SIGNIN_FAILED';

// Multiple Characters Types
export const CHARACTER_LOAD_STARTED = 'CHARACTER_LOAD_STARTED';
export const CHARACTER_LOAD_SUCCESS = 'CHARACTER_LOAD_SUCCESS';
export const CHARACTER_LOAD_ERROR = 'CHARACTER_LOAD_ERROR';
export const LOCAL_CHARACTER_LOAD_FAILED = 'LOCAL_CHARACTER_LOAD_FAILED';

// Singe Character Types
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const CHARACTER_DETAILS_LOAD_STARTED = 'CHARACTER_DETAILS_LOAD_STARTED';
export const CHARACTER_DETAILS_LOAD_SUCCESS = 'CHARACTER_DETAILS_LOAD_SUCCESS';

// Attribute Types
export const ATTRIBUTE_LOAD_STARTED = 'ATTRIBUTE_LOAD_STARTED';
export const ATTRIBUTE_LOAD_SUCCESS = 'ATTRIBUTE_LOAD_SUCCESS';
export const ATTRIBUTE_LOAD_ERROR = 'ATTRIBUTE_LOAD_ERROR';
