// Auth types
export const SIGNOUT = 'SIGNOUT';
export const SIGNIN_STARTED = 'SIGNIN_STARTED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const LOCAL_SIGNIN_FAILED = 'LOCAL_SIGNIN_FAILED';

// Multiple Characters Types
export const CHARACTER_LOAD_STARTED = 'CHARACTER_LOAD_STARTED';
export const CHARACTER_LOAD_SUCCESS = 'CHARACTER_LOAD_SUCCESS';
export const CHARACTER_LOAD_ERROR = 'CHARACTER_LOAD_ERROR';
export const LOCAL_CHARACTER_LOAD_FAILED = 'LOCAL_CHARACTER_LOAD_FAILED';

// Singe Character Types
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const CHARACTER_DETAILS_LOAD_STARTED = 'CHARACTER_DETAILS_LOAD_STARTED';
export const CHARACTER_DETAILS_LOAD_SUCCESS = 'CHARACTER_DETAILS_LOAD_SUCCESS';
export const ADD_CHARACTER = 'ADD_CHARACTER';
// start actions
export const UPDATE_EQUIPMENT_QUANTITY_START = 'UPDATE_EQUIPMENT_QUANTITY_START';
export const REMOVE_ATTRIBUTE_START = 'REMOVE_ATTRIBUTE_START';
export const NUMERIC_UPDATE_START = 'NUMERIC_UPDATE_START';
export const UPDATE_CHARACTER_START = 'UPDATE_CHARACTER_START';
// generic success and error actions
export const UPDATE_CHARACTER_SUCCESS = 'UPDATE_CHARACTER_SUCCESS';
export const UPDATE_EQUIPMENT_SUCCESS = 'UPDATE_EQUIPMENT_SUCCESS';
export const UPDATE_CHARACTER_ERROR = 'UPDATE_CHARACTER_ERROR';


// Search Types
export const SEARCH_LOAD_STARTED = 'SEARCH_LOAD_STARTED';
export const SEARCH_LOAD_SUCCESS = 'SEARCH_LOAD_SUCCESS';
export const SEARCH_LOAD_ERROR = 'SEARCH_LOAD_ERROR';
export const CACHE_RESULT = 'CACHE_RESULT';

// New Character Options Types
export const OPTIONS_LOAD_STARTED = 'OPTIONS_LOAD_STARTED';
export const OPTIONS_LOAD_SUCCESS = 'OPTIONS_LOAD_SUCCESS';
export const OPTIONS_LOAD_ERROR = 'OPTIONS_LOAD_ERROR';
export const SET_CHARACTER_FIELD = 'SET_CHARACTER_FIELD';
export const CHARACTER_SUBMIT_STARTED = 'CHARACTER_SUBMIT_STARTED';
export const CHARACTER_SUBMIT_ERROR = 'CHARACTER_SUBMIT_ERROR';
