export default {
	isMobile: false,
	auth: {
		token: null,
		loading: false,
		error: null,
		checkedLocal: false,
		user: null,
	},
	characters: {
		fetched: false,
		loading: false,
		data: {},
		prevData: null,
		error: null,
	},
	search: {
		feats: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		features: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		skills: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		proficiencies: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		spells: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		equipment: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		languages: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		conditions: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
		traits: {
			loading: false,
			fetched: false,
			error: null,
			data: [],
			cache: {},
		},
	},
	new: {
		loading: false,
		error: null,
		submitted: false,
		character: {
			name: '',
			race: null,
			characterClass: null,
			level: 0,
			dexterity: 0,
			strength: 0,
			constitution: 0,
			wisdom: 0,
			intelligence: 0,
			charisma: 0,
		},
	},
};
